name: Deploy staging

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to branch
    runs-on: ubuntu-latest
#    needs: validate
    steps:
      - uses: actions/checkout@v4

#      - name: Login to registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ secrets.DOCKER_REGISTRY }}
#          username: ${{ secrets.DOCKER_LOGIN }}
#          password: ${{ secrets.DOCKER_PASSWD }}

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: ${{ secrets.DOCKER_REGISTRY }}/degov:${{ github.ref_name }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST_PREPROD }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Update branch environment
        env:
          DOCKER_BRANCH: ${{ github.ref_name }}
#          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
#          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
#          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
          DOMAIN_URL: ${{ secrets.DOMAIN_URL_PREPROD }}
          CHAIN_RPC_1: ${{ secrets.CHAIN_RPC_1 }}
          CHAIN_RPC_100: ${{ secrets.CHAIN_RPC_100 }}
          DEGOV_DB_PASSWORD: ${{ secrets.DEGOV_DB_PASSWORD }}
          DEGOV_WEB_JWT_SECRET: ${{ secrets.DEGOV_WEB_JWT_SECRET }}
          DEGOV_SYNC_AUTH_TOKEN: ${{ secrets.DEGOV_SYNC_AUTH_TOKEN }}

        run: |
          if [[ "$DOCKER_BRANCH" == "main" ]]; then
            export HOSTNAME="degov.$DOMAIN_URL"
          elif [[ "$DOCKER_BRANCH" == "preprod" ]]; then
            export HOSTNAME="degov.$DOCKER_BRANCH.$DOMAIN_URL"
          else
            export HOSTNAME="degov.$DOCKER_BRANCH.$DOMAIN_URL"
          fi

          ssh staging <<EOF
            set -euxo pipefail
            export DOCKER_BRANCH="$DOCKER_BRANCH"
#            export DOCKER_REGISTRY="$DOCKER_REGISTRY"

            cd /var/docker/degov/git
            git pull origin \$DOCKER_BRANCH
            docker compose --file docker-compose.yml pull
#            docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWD" \$DOCKER_REGISTRY

            CHAIN_RPC_1="$CHAIN_RPC_1"
            CHAIN_RPC_100="$CHAIN_RPC_100"
            DEGOV_DB_PASSWORD="$DEGOV_DB_PASSWORD"
            DEGOV_WEB_JWT_SECRET="$DEGOV_WEB_JWT_SECRET"
            DEGOV_SYNC_AUTH_TOKEN="$DEGOV_SYNC_AUTH_TOKEN"
            HOSTNAME="$HOSTNAME" \
            docker compose --project-name \$DOCKER_BRANCH-degov --file docker-compose.yml up -d
          EOF
